export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_LOADING = 'REGISTER_LOADING'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_LOADING = 'LOGIN_LOADING'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_LOADING = 'GET_USER_LOADING'

export const SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL'
export const SEND_RESET_PASSWORD_EMAIL_SUCCESS = 'SEND_RESET_PASSWORD_EMAIL_SUCCESS'
export const SEND_RESET_PASSWORD_EMAIL_FAILED = 'SEND_RESET_PASSWORD_EMAIL_FAILED'
export const SEND_RESET_PASSWORD_EMAIL_LOADING = 'SEND_RESET_PASSWORD_EMAIL_LOADING'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'
export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const GOOGLE_LOGGED_IN = 'GOOGLE_LOGGED_IN'

export const VERIFY_USER = 'VERIFY_USER'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILED = 'VERIFY_USER_FAILED'
export const VERIFY_USER_LOADING = 'VERIFY_USER_LOADING'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING'

export const GET_DISPLAY = 'GET_DISPLAY'
export const GET_DISPLAY_SUCCESS = 'GET_DISPLAY_SUCCESS'
export const GET_DISPLAY_FAILED = 'GET_DISPLAY_FAILED'
export const GET_DISPLAY_LOADING = 'GET_DISPLAY_LOADING'

export const GET_TAG_DISPLAY = 'GET_TAG_DISPLAY'
export const GET_TAG_DISPLAY_SUCCESS = 'GET_TAG_DISPLAY_SUCCESS'
export const GET_TAG_DISPLAY_FAILED = 'GET_TAG_DISPLAY_FAILED'
export const GET_TAG_DISPLAY_LOADING = 'GET_TAG_DISPLAY_LOADING'

export const ADD_DISPLAY = 'ADD_DISPLAY'
export const ADD_DISPLAY_SUCCESS = 'ADD_DISPLAY_SUCCESS'
export const ADD_DISPLAY_FAILED = 'ADD_DISPLAY_FAILED'
export const ADD_DISPLAY_LOADING = 'ADD_DISPLAY_LOADING'

export const UPDATE_DISPLAY = 'UPDATE_DISPLAY'
export const UPDATE_DISPLAY_SUCCESS = 'UPDATE_DISPLAY_SUCCESS'
export const UPDATE_DISPLAY_FAILED = 'UPDATE_DISPLAY_FAILED'
export const UPDATE_DISPLAY_LOADING = 'UPDATE_DISPLAY_LOADING'

export const GET_TAG = 'GET_TAG'
export const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS'
export const GET_TAG_FAILED = 'GET_TAG_FAILED'
export const GET_TAG_LOADING = 'GET_TAG_LOADING'

export const ADD_TAG = 'ADD_TAG'
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS'
export const ADD_TAG_FAILED = 'ADD_TAG_FAILED'
export const ADD_TAG_LOADING = 'ADD_TAG_LOADING'

export const UPDATE_TAG = 'UPDATE_TAG'
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS'
export const UPDATE_TAG_FAILED = 'UPDATE_TAG_FAILED'
export const UPDATE_TAG_LOADING = 'UPDATE_TAG_LOADING'

export const DELETE_TAG = 'DELETE_TAG'
export const DELETE_TAG_SUCCESS = 'UDELETE_TAG_SUCCESS'
export const DELETE_TAG_FAILED = 'DELETE_TAG_FAILED'
export const DELETE_TAG_LOADING = 'DELETE_TAG_LOADING'

export const GET_ASSET = 'GET_ASSET'
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS'
export const GET_ASSET_FAILED = 'GET_ASSET_FAILED'
export const GET_ASSET_LOADING = 'GET_ASSET_LOADING'

export const GET_ASSET_TAGS = 'GET_ASSET_TAGS'
export const GET_ASSET_TAGS_SUCCESS = 'GET_ASSET_TAGS_SUCCESS'
export const GET_ASSET_TAGS_FAILED = 'GET_ASSET_TAGS_FAILED'
export const GET_ASSET_TAGS_LOADING = 'GET_ASSET_TAGS_LOADING'

export const ADD_ASSET = 'ADD_ASSET'
export const ADD_ASSET_SUCCESS = 'ADD_ASSET_SUCCESS'
export const ADD_ASSET_FAILED = 'ADD_ASSET_FAILED'
export const ADD_ASSET_LOADING = 'ADD_ASSET_LOADING'

export const UPDATE_ASSET = 'UPDATE_ASSET'
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS'
export const UPDATE_ASSET_FAILED = 'UPDATE_ASSET_FAILED'
export const UPDATE_ASSET_LOADING = 'UPDATE_ASSET_LOADING'

export const DELETE_ASSET = 'DELETE_ASSET'
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS'
export const DELETE_ASSET_FAILED = 'DELETE_ASSET_FAILED'
export const DELETE_ASSET_LOADING = 'DELETE_ASSET_LOADING'

export const GET_COMPOSITION = 'GET_COMPOSITION'
export const GET_COMPOSITION_SUCCESS = 'GET_COMPOSITION_SUCCESS'
export const GET_COMPOSITION_FAILED = 'GET_COMPOSITION_FAILED'
export const GET_COMPOSITION_LOADING = 'GET_COMPOSITION_LOADING'

export const ADD_COMPOSITION = 'ADD_COMPOSITION'
export const ADD_COMPOSITION_SUCCESS = 'ADD_COMPOSITION_SUCCESS'
export const ADD_COMPOSITION_FAILED = 'ADD_COMPOSITION_FAILED'
export const ADD_COMPOSITION_LOADING = 'ADD_COMPOSITION_LOADING'

export const UPDATE_COMPOSITION = 'UPDATE_COMPOSITION'
export const UPDATE_COMPOSITION_SUCCESS = 'UPDATE_COMPOSITION_SUCCESS'
export const UPDATE_COMPOSITION_FAILED = 'UPDATE_COMPOSITION_FAILED'
export const UPDATE_COMPOSITION_LOADING = 'UPDATE_COMPOSITION_LOADING'

export const UPDATE_COMPOSITION_TEMPLATE = 'UPDATE_COMPOSITION_TEMPLATE'
export const UPDATE_COMPOSITION_TEMPLATE_SUCCESS = 'UPDATE_COMPOSITION_TEMPLATE_SUCCESS'
export const UPDATE_COMPOSITION_TEMPLATE_FAILED = 'UPDATE_COMPOSITION_TEMPLATE_FAILED'
export const UPDATE_COMPOSITION_TEMPLATE_LOADING = 'UPDATE_COMPOSITION_TEMPLATE_LOADING'

export const DELETE_COMPOSITION = 'DELETE_COMPOSITION'
export const DELETE_COMPOSITION_SUCCESS = 'DELETE_COMPOSITION_SUCCESS'
export const DELETE_COMPOSITION_FAILED = 'DELETE_COMPOSITION_FAILED'
export const DELETE_COMPOSITION_LOADING = 'DELETE_COMPOSITION_LOADING'

export const GET_SCHEDULE_COMPOSITION = 'GET_SCHEDULE_COMPOSITION'
export const GET_SCHEDULE_COMPOSITION_SUCCESS = 'GET_SCHEDULE_COMPOSITION_SUCCESS'
export const GET_SCHEDULE_COMPOSITION_FAILED = 'GET_SCHEDULE_COMPOSITION_FAILED'
export const GET_SCHEDULE_COMPOSITION_LOADING = 'GET_SCHEDULE_COMPOSITION_LOADING'

export const ADD_SCHEDULE_COMPOSITION = 'ADD_SCHEDULE_COMPOSITION'
export const ADD_SCHEDULE_COMPOSITION_SUCCESS = 'ADD_SCHEDULE_COMPOSITION_SUCCESS'
export const ADD_SCHEDULE_COMPOSITION_FAILED = 'ADD_SCHEDULE_COMPOSITION_FAILED'
export const ADD_SCHEDULE_COMPOSITION_LOADING = 'ADD_SCHEDULE_COMPOSITION_LOADING'

export const UPDATE_SCHEDULE_COMPOSITION = 'UPDATE_SCHEDULE_COMPOSITION'
export const UPDATE_SCHEDULE_COMPOSITION_SUCCESS = 'UPDATE_SCHEDULE_COMPOSITION_SUCCESS'
export const UPDATE_SCHEDULE_COMPOSITION_FAILED = 'UPDATE_SCHEDULE_COMPOSITION_FAILED'
export const UPDATE_SCHEDULE_COMPOSITION_LOADING = 'UPDATE_SCHEDULE_COMPOSITION_LOADING'

export const DELETE_SCHEDULE_COMPOSITION = 'DELETE_SCHEDULE_COMPOSITION'
export const DELETE_SCHEDULE_COMPOSITION_SUCCESS = 'DELETE_SCHEDULE_COMPOSITION_SUCCESS'
export const DELETE_SCHEDULE_COMPOSITION_FAILED = 'DELETE_SCHEDULE_COMPOSITION_FAILED'
export const DELETE_SCHEDULE_COMPOSITION_LOADING = 'DELETE_SCHEDULE_COMPOSITION_LOADING'

export const GET_SCHEDULE = 'GET_SCHEDULE'
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_FAILED = 'GET_SCHEDULE_FAILED'
export const GET_SCHEDULE_LOADING = 'GET_SCHEDULE_LOADING'

export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS'
export const ADD_SCHEDULE_FAILED = 'ADD_SCHEDULE_FAILED'
export const ADD_SCHEDULE_LOADING = 'ADD_SCHEDULE_LOADING'

export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE'
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS'
export const UPDATE_SCHEDULE_FAILED = 'UPDATE_SCHEDULE_FAILED'
export const UPDATE_SCHEDULE_LOADING = 'UPDATE_SCHEDULE_LOADING'

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS'
export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED'
export const DELETE_SCHEDULE_LOADING = 'DELETE_SCHEDULE_LOADING'

export const GET_TEMPLATE = 'GET_TEMPLATE'
export const GET_TEMPLATE_SUCCESS = 'GET_TEMPLATE_SUCCESS'
export const GET_TEMPLATE_FAILED = 'GET_TEMPLATE_FAILED'
export const GET_TEMPLATE_LOADING = 'GET_TEMPLATE_LOADING'

export const GET_DEFAULT_TEMPLATE = 'GET_DEFAULT_TEMPLATE'
export const GET_DEFAULT_TEMPLATE_SUCCESS = 'GET_DEFAULT_TEMPLATE_SUCCESS'
export const GET_DEFAULT_TEMPLATE_FAILED = 'GET_DEFAULT_TEMPLATE_FAILED'
export const GET_DEFAULT_TEMPLATE_LOADING = 'GET_DEFAULT_TEMPLATE_LOADING'

export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS'
export const ADD_TEMPLATE_FAILED = 'ADD_TEMPLATE_FAILED'
export const ADD_TEMPLATE_LOADING = 'ADD_TEMPLATE_LOADING'

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS'
export const UPDATE_TEMPLATE_FAILED = 'UPDATE_TEMPLATE_FAILED'
export const UPDATE_TEMPLATE_LOADING = 'UPDATE_TEMPLATE_LOADING'

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS'
export const DELETE_TEMPLATE_FAILED = 'DELETE_TEMPLATE_FAILED'
export const DELETE_TEMPLATE_LOADING = 'DELETE_TEMPLATE_LOADING'

export const GET_ZONE_ASSET = 'GET_ZONE_ASSET'
export const GET_ZONE_ASSET_SUCCESS = 'GET_ZONE_ASSET_SUCCESS'
export const GET_ZONE_ASSET_FAILED = 'GET_ZONE_ASSET_FAILED'
export const GET_ZONE_ASSET_LOADING = 'GET_ZONE_ASSET_LOADING'

export const ADD_ZONE_ASSET = 'ADD_ZONE_ASSET'
export const ADD_ZONE_ASSET_SUCCESS = 'ADD_ZONE_ASSET_SUCCESS'
export const ADD_ZONE_ASSET_FAILED = 'ADD_ZONE_ASSET_FAILED'
export const ADD_ZONE_ASSET_LOADING = 'ADD_ZONE_ASSET_LOADING'

export const UPDATE_ZONE_ASSET = 'UPDATE_ZONE_ASSET'
export const UPDATE_ZONE_ASSET_SUCCESS = 'UPDATE_ZONE_ASSET_SUCCESS'
export const UPDATE_ZONE_ASSET_FAILED = 'UPDATE_ZONE_ASSET_FAILED'
export const UPDATE_ZONE_ASSET_LOADING = 'UPDATE_ZONE_ASSET_LOADING'

export const DELETE_ZONE_ASSET = 'DELETE_ZONE_ASSET'
export const DELETE_ZONE_ASSET_SUCCESS = 'DELETE_ZONE_ASSET_SUCCESS'
export const DELETE_ZONE_ASSET_FAILED = 'DELETE_ZONE_ASSET_FAILED'
export const DELETE_ZONE_ASSET_LOADING = 'DELETE_ZONE_ASSET_LOADING'

export const GET_APP = 'GET_APP'
export const GET_APP_SUCCESS = 'GET_APP_SUCCESS'
export const GET_APP_FAILED = 'GET_APP_FAILED'
export const GET_APP_LOADING = 'GET_APP_LOADING'

export const ADD_APP = 'ADD_APP'
export const ADD_APP_SUCCESS = 'ADD_APP_SUCCESS'
export const ADD_APP_FAILED = 'ADD_APP_FAILED'
export const ADD_APP_LOADING = 'ADD_APP_LOADING'

export const UPDATE_APP = 'UPDATE_APP'
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS'
export const UPDATE_APP_FAILED = 'UPDATE_APP_FAILED'
export const UPDATE_APP_LOADING = 'UPDATE_APP_LOADING'

export const DELETE_APP = 'DELETE_APP'
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS'
export const DELETE_APP_FAILED = 'DELETE_APP_FAILED'
export const DELETE_APP_LOADING = 'DELETE_APP_LOADING'

export const DEFAULT_TEMPLATE = 'DEFAULT_TEMPLATE'
export const CURRENT_COMPOSITION = 'CURRENT_COMPOSITION'

export const UPDATE_DISPLAY_DEFAULT_COMPOSITION = 'UPDATE_DISPLAY_DEFAULT_COMPOSITION'
export const UPDATE_DISPLAY_DEFAULT_COMPOSITION_SUCCESS = 'UPDATE_DISPLAY_DEFAULT_COMPOSITION_SUCCESS'
export const UPDATE_DISPLAY_DEFAULT_COMPOSITION_FAILED = 'UPDATE_DISPLAY_DEFAULT_COMPOSITION_FAILED'
export const UPDATE_DISPLAY_DEFAULT_COMPOSITION_LOADING = 'UPDATE_DISPLAY_DEFAULT_COMPOSITION_LOADING'

export const GET_LOG = 'GET_LOG'
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS'
export const GET_LOG_FAILED = 'GET_LOG_FAILED'
export const GET_LOG_LOADING = 'GET_LOG_LOADING'